### PR TITLE
Helper methods for tsvector_column (auto)rebuilding

### PR DESCRIPTION
**Pull request by marshall-lee**
Hello!
Please see updated [README](https://github.com/marshall-lee/pg_search/blob/tsvector_autoupdate/README.md) for details.
Summary: It makes possible to avoid creating database triggers and, in some cases, avoid using `:sql` schema format. For example, in my project i use only `pg_search_scope` feature and none of pg_search features that require writing raw sql migrations, so i can use nice and clean `schema.rb` instead of raw sql. Now i do tsvector rebuilding in `after_save` callback which is the right way to do such things rather than using postgresql triggers.

If you ready to take this, i can go further and implement support for `dmetaphone` in similar way. Please let me know what i might fix or refactor.

### CODE REVIEW

**Comment by marshall-lee** [comment]
Bump!

**Comment by marshall-lee** [comment]
I realized a little problem with my code.
During initialization `PgSearch::Configuration.new` causes `PgSearch::Configuration::Column.new` which calls `model.connection`. It causes acquiring connection from pool and not automatically takes it back. Normally, inside Action Pack request cycle all acquired connections are normally released by rack middleware but during application initialization it doesn't happen so our connection pool doesn't get the connection back. It doesn't affect single-thread environment (unicorn) but in multithreaded it's bad.

I think, `PgSearch` we must replace every `model.connection` call with `model.connection_pool.with_connection { |connection| ... }` to fix this issue and for future safety.

**Comment by marshall-lee** [comment]
Last commit fixes issue with connection acquiring during initialization.

**Comment by arkadiybutermanov** [comment]
:+1

**Pull request closed without merging**
