### PR TITLE
Fix issue 235

### PR DESCRIPTION
**Pull request by doits**
Unfortunately now an other test fails, didn't inspect it yet.

### CODE REVIEW

**Comment by doits** [comment]
When we explicitly remove the `where` and `joins`, a `.dup` is not needed anymore. Now all tests pass.

I think the main issue (which might affect other portions is pg_search, too) is that `model` is modified somewhere in the code and then affects other portions of the code where it should not be modified.

**Comment by nertzy** [comment]
Makes sense that we don't want the `where` and `joins` to leak into the subquery.

Overall this looks good. Please squash everything down to one commit and I will merge this.

**Comment by doits** [comment]
Rebase done.

**Comment by doits** [comment]
I'm not sure, but maybe replacing `.except(:joins).except(:where)` with `.unscoped` is cleaner (and removes everything else what could be a problem in the future?)

**Comment by nertzy** [comment]
Merged all the way into master. I like the `.unscoped` idea, definitely worth a shot!

**Pull request merged**
