### PR TITLE
column: add support for Arel::Nodes::SqlLiteral

### LINKED ISSUE #252: Search against jsonb
Hi,

Is there any official way to include jsonb fields in search_scopes? 

I've tried adding them as strings, but it doesn't work.

`pg_search_scope :search, against: [:foo,  "data->>'name'"]`

Digging into it, I've found that when pg_search builds the query, it quotes column names and generates 
something like this:
`(ts_rank((to_tsvector('simple', COALESCE("trials"."imported_data->>'title'"::text, ''))`

while Postgres expects this:
`(ts_rank((to_tsvector('simple', COALESCE("trials".imported_data->>'title'::text, ''))`

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #252, allowing for more more advanced columns, such as extracting elements out of json arrays, or fields out of json objects. This is intended to be entirely backward compatible.

### CODE REVIEW

**Review by nertzy — APPROVED** [review]

**Comment by chiperific** [comment]
Is this going to be released? I don't see this code in v.2.3.6

**Comment by egrueter-dev** [comment]
Can we get some proper documentation about how to use this?

**Comment by comictvn** [comment]
> Can we get some proper documentation about how to use this?

me too

**Comment by diddeb** [comment]
➕ 1️⃣ on the docs. Or just a stupid-simple example for moots like myself.

**Comment by kalashnikovisme** [comment]
Found something useful in tests. An example, that works for me:

```ruby
class Car < ApplicationRecord
  store_accessor :options, :number
end

class Driver < ApplicationRecord
  has_many :cars

  pg_search_scope(
    :pg_search,
    against: [:first_name, :last_name, :middle_name],
    associated_against: {
      cars: [Arel.sql("cars.options->>'number'")]
    },
    using: { tsearch: { prefix: true } }
  )
end
```

But looks like `tsearch` does not work for `"cars.options->>'number'")` column. Trying to fix it right now. It works well for `first_name, etc.` of `Driver` still.

**Comment by jakemcallister** [comment]
did you ever get this working?

**Pull request merged**
